### ISSUE TITLE
Workshop Conducted Remains on 200

### ISSUE THREAD

**Issue by tiaradwiputri** [onlyphantom/pedagogy#24]
Cross checked on DB supposedly 211 per 15 April 2019.

Problem should be related to global_total_stats() function on analytics.py query.

**Comment by onlyphantom** [comment]
I suspect it has to do with the behaviour from the specific db we’re using; when querying a db using a middleware unless explicitly asked for, only the first 200 rows (or the db / middleware default) is returned for practical reasons.

Say you ask for column names of a db, it doesn’t need to load the entire db for that, so it loads a default (let’s say 200 rows) and then it would already be able to tell the colnames.

I’m not sure that is the case here though, but that’s my guess because the counter was working all the way up till 200 then it stop updating

**Comment by onlyphantom** [comment]
Solved by Restarting the server and db
