### ISSUE TITLE
Survey URL Accessibility

### ISSUE THREAD

**Issue by ardhitoutomo** [onlyphantom/pedagogy#8]
![image](https://user-images.githubusercontent.com/40533325/52085681-abadc800-25d7-11e9-868e-227b76ba2a49.png)
![image](https://user-images.githubusercontent.com/40533325/52085645-933dad80-25d7-11e9-89cd-613100d967a3.png)
It looks like almost all survey from the past workshop is still accessible. I'm not sure it's everything because we already had 142 workshops, hence 142 surveys, but the number stop at 130 and once I access survey/131 it takes me back to the index page and returns this
![image](https://user-images.githubusercontent.com/40533325/52086065-8ff6f180-25d8-11e9-95b8-c8acfad2b477.png)

**Comment by onlyphantom** [comment]
I've implemented a simple expiry system so survey forms for past workshops beyond certain duration (currently: 10 days) will no longer be accessible. I know it may not be the most elegant or robust - but for our business use-case this suffice.

Post the Alpha version release, I may consider changing the database models to implement a certain "survey open" check. This adds more process on the administrative side to be sure, but it make sure participants can rate a workshop only when (survey.open == True) and will not be able to access the survey form otherwise. Then our general affairs team need to manually turn survey open / closed - which I'm not very keen on :/ 

To me: practicality and less-process is preferable. If there's any ideas - please propose and maybe we can consider after the Alpha version release. For now the expiry system works 😃

**Comment by onlyphantom** [comment]
+ Pushing to production version
